title: "[EVENT] "
labels: ["EVENT TO PUBLISH"]
body:
  - type: input
    id: event-name
    attributes:
      label: Event Name
      description: |
        The name of the event.
        It's this name that will show up on the calendar, not the thread title above.
      value: 🎉 Exciting New Event
    validations:
      required: true
  - type: textarea
    id: event-description
    attributes:
      label: Event Description
      description: |
        The text body of the calendar event.
        Use Unicode only (no Markdown/HTML, but emojis are OK).
      value: |
        Description of the event goes here.
    validations:
      required: true
  - type: input
    id: start-time
    attributes:
      label: Start Time
      description: |
        Start time in 'YYYY-MM-DD HH:MM:SS' format in Swiss local time (summer time will
        be handled automatically). For all-day/multi-day events (e.g. ski retreat), just
        provide 'YYYY-MM-DD' alone (inclusive).
      value: 2025-12-12 17:00:00
    validations:
      required: true
  - type: input
    id: end-time
    attributes:
      label: End Time
      description: |
        End time in 'YYYY-MM-DD HH:MM:SS' format in Swiss local time (summer time will
        be handled automatically). For all-day/multi-day events (e.g. ski retreat), just
        provide 'YYYY-MM-DD' alone (inclusive).
      value: 2025-12-12 21:00:00
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      description: Location of the event.
      value: SV lobby
    validations:
      required: true
